name: sinae_flutter
description: test mini shopping mall

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_icons:
  flutter_localizations:
    sdk: flutter
  get: ^4.3.8  # getX : required >> flutter run --no-sound-null-safety ^4.3.8
  convert: ^3.0.1
  intl: ^0.17.0  # number format

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.3
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/data/products.json
    - assets/data/categories.json
    - assets/data/board.json
  fonts:
    - family: ArchitypeRenner
      fonts:
        - asset: assets/fonts/ArchitypeRenner-Demi.otf
        - asset: assets/fonts/ArchitypeRenner-Bold.otf
          weight: 700
